nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: '%env(resolve:json:CORS_ALLOW_ORIGIN)%'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers:
            - 'Content-Type'
            - 'Authorization'
            - 'X-Company-Id'
            - 'X-Session-Id'
            - 'X-Requested-With'
            - 'Accept'
            - 'Origin'
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': ~
        '^/auth/': ~
